### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by snegodick** [R4stl1n/SSH-Brute-Forcer#1]
~/SSH-Brute-Forcer/src# python SSHBruteForce.py -I ip -U u -P p
Traceback (most recent call last):
  File "SSHBruteForce.py", line 265, in <module>
    sshBruteForce.startUp()
  File "SSHBruteForce.py", line 98, in startUp
    elif not options.targetIp and options.targetsFilet:
AttributeError: Values instance has no attribute 'targetsFilet'

**Comment by r4stl1n** [comment]
Sorry about that these never showed up on my notifications. Issues have been fixed.

**Comment by Pfanner** [comment]
python SSHBruteForce.py -i 192.168.180.22 -p 22 -a 100 -l 8
Traceback (most recent call last):
  File "SSHBruteForce.py", line 265, in <module>
    sshBruteForce.startUp()
  File "SSHBruteForce.py", line 97, in startUp
    self.singleTarget(options)
  File "SSHBruteForce.py", line 120, in singleTarget
    self.bruteForceSingle();
  File "SSHBruteForce.py", line 185, in bruteForceSingle
    for x in range(self.bruteForceAttempts):
TypeError: range() integer end argument expected, got str.

**Comment by r4stl1n** [comment]
Its been fixed.

**Comment by Pfanner** [comment]
python SSHBruteForce.py -I ./targets.txt -d True -p 22 -U ./usernames.txt -P ./passwords.txt -t 15 -T 30
[_] Simple SSH Brute Forcer: By r4stl1n
[_] Loaded 82495 Targets
[_] Loaded 172 Usernames
[_] Loaded 222 Passwords
[*] Brute Force Starting
No handlers could be found for logger "paramiko.transport"

**Comment by r4stl1n** [comment]
add -v for verbose output

**Comment by degenerat** [comment]
python SSHBruteForce.py -I -U .-P -t 100 -O 
Traceback (most recent call last):
  File "SSHBruteForce.py", line 263, in <module>
    sshBruteForce.startUp()
  File "SSHBruteForce.py", line 96, in startUp
    elif not options.targetIp and options.targetsFilet:
AttributeError: Values instance has no attribute 'targetsFilet'

**Comment by hillsbird** [comment]
It happend again:
Traceback (most recent call last):
  File "SSHBruteForce.py", line 280, in <module>
    sshBruteForce.startUp()
  File "SSHBruteForce.py", line 98, in startUp
    elif not options.targetIp and options.targetsFilet:
AttributeError: Values instance has no attribute 'targetsFilet'

**Comment by nimicent** [comment]
I am getting this error ^ as well. You have any idea what this is? Can't use your wonderful code...

```
python SSHBruteForce.py -I targets.txt -p 22 -a 100 -l 8 -v
Traceback (most recent call last):
  File "SSHBruteForce.py", line 280, in <module>
    sshBruteForce.startUp()
  File "SSHBruteForce.py", line 98, in startUp
    elif not options.targetIp and options.targetsFilet:
AttributeError: Values instance has no attribute 'targetsFilet'

```
