### ISSUE TITLE
Codec 'utf-8' cant decode byte "0xf1" in position 923: Error using rockyou.txt

### ISSUE THREAD

**Issue by Jul10l1r4** [R4stl1n/SSH-Brute-Forcer#20]
Machine: Wifislax (Slackware likely)
```python
Traceback (most recent call last):
  File "SSHBruteForce.py", line 282, in <module>
    sshBruteForce.startUp()
  File "SSHBruteForce.py", line 82, in startUp
    self.singleTarget(options)
  File "SSHBruteForce.py", line 119, in singleTarget
    self.passwords = Util.fileContentsToList(options.passwordsFile)
  File "/root/SSH-Brute-Forcer/src/Util.py", line 20, in fileContentsToList
    for line in fileParser.readlines():
  File "/usr/lib64/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 923: invalid continuation byte
```

**Comment by FujiwaraChoki** [comment]
How was this solved?
